[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "noncon"
version = "0.0.1"
description = "Conformal anomaly detection with 'PyOD' detectors."
authors = [
  { name = "Oliver Hennhoefer", email = "oliver.hennhoefer@mail.de" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
    "numpy ~=1.26.4",
    "pandas ~=2.2.1",
    "pyod ~=1.1.3",
    "scipy ~=1.13.0",
    "tensorflow ~=2.16.1",
    "torch ~=2.2.2",
    "tqdm ~=4.66.2"
]

[project.urls]
"Homepage" = "https://github.com/OliverHennhoefer/noncon"
"Bugs" = "https://github.com/OliverHennhoefer/noncon/issues"
